### ISSUE TITLE
[REQUEST]Option to hide "Check for updates" and "About" in context menu

### ISSUE THREAD

**Issue by devRolige** [infinitepower18/WSA-SystemControl#14]
### Describe your request

Could you add this options for example in config file?
You could also add the option of adding your own shortcuts to Android apps.

**Comment by infinitepower18** [comment]
A settings screen is coming, once that's implemented I will look into adding these options as well as #6.

FYI, the check for updates option is not visible on the MS Store version since you use the MS Store app to check for updates.

**Comment by devRolige** [comment]
@infinitepower18 I used winget to install and I also use winget to check for updates. 
Is it possible to install the MS Store version on Windows 10?

![Zrzut ekranu 2023-07-29 162527](https://github.com/infinitepower18/WSA-SystemControl/assets/82973050/91bd1b31-9937-46a4-8591-b0586423a868)

**Comment by infinitepower18** [comment]
MS Store version is only for Windows 11, sorry.
