### ISSUE TITLE
[REQUEST] Disable starting of WSA when WSA-SystemControl taskbar icon is clicked/tapped

### ISSUE THREAD

**Issue by richaardvark** [infinitepower18/WSA-SystemControl#16]
### Describe your request

Hello :)

I love this tool - thank you so very much for making it! I have one issue though... the touchpad on my laptop is annoyingly over-sensitive despite my adjusting it and every time I try to close/exit WSA-SystemControl by selecting the icon from the taskbar after I've already shut it down it instantly restarts WSA again and it's super frustrating. Could this be an adjustable option somewhere, being able to set it to simply show the right-click/context menu when it is selected and WSA is stopped instead of restarting WSA every time?  There is already a menu option in the context menu to "Start WSA" and I would really like if that was the only way to accomplish this.  Thank you for making such a great tool!

**Comment by infinitepower18** [comment]
Hi, thanks for the feedback. I have plans to add a settings page and will add an option to change the left click behaviour.

**Comment by infinitepower18** [comment]
As Microsoft has discontinued work on the subsystem, this application is now in maintenance mode, meaning no new updates will be released apart from bug fixes. For more information please see #22. Thank you for your understanding and sorry if this decision disappointed you.
