### ISSUE TITLE
[REQUEST] Automatic ADB commands

### ISSUE THREAD

**Issue by Fummowo** [infinitepower18/WSA-SystemControl#18]
### Describe your request

WSA doesn't save settings after rebooting which can be quite infuriating.
I have tried using Magisk startup scripts, but they seem to not execute after WSA has finished booting, even with an added sleep.

It would be a really nice feature for this to automatically detect once WSA has fully started (or just on a delay from when it detects it starting up) and automatically send commands over ADB.

This way, most settings can be re-applied on startup, and allows for much more!
An option to provide a current install of ADB would also be useful (if an automatic install were to exist)

I thought this would make the most sense for this application as it is a constant background process based around WSA :)
Personally, I would use this to adjust the dpi of my second monitor so that everything isn't so small when it's in fullscreen:
`adb shell wm density 380 -d 2`

(Great work btw, this is a very nice application)

Edit:
Immediately after posting, I realized that adding ADB functionality would probably help with the Restart feature from https://github.com/infinitepower18/WSA-SystemControl/issues/1

**Comment by infinitepower18** [comment]
Hi, thanks for the suggestion 🙂 I will think about it.

While the restart functionality can be achieved through adb, I had wanted to avoid relying on adb for the core functionality of the app as it's not always reliable. Also, I'm not sure if it will be a good user experience if adb and developer mode is needed just for the restart option, while the power on and off options can be done through built in WSAClient commands.

I can think about having adb for running commands on startup. Perhaps an option in the settings to provide a batch file of commands?

Currently in my other program, WSA Sideloader, I bundle in a version of adb that's guaranteed to work properly, so I might take a similar approach if I integrate it into this app.

**Comment by infinitepower18** [comment]
As Microsoft has discontinued work on the subsystem, this application is now in maintenance mode, meaning no new updates will be released apart from bug fixes. For more information please see #22. Thank you for your understanding and sorry if this decision disappointed you.
