### ISSUE TITLE
Open WSA sideloader

### ISSUE THREAD

**Issue by ghost** [infinitepower18/WSA-SystemControl#4]
### Describe your request

I think adding an option to launch your Side-loader app, would streamline things. Having all your WSA needs right in one panel would be great!

**Comment by infinitepower18** [comment]
I was thinking of doing that, but I need to find a way to detect if WSA Sideloader is installed, and if not it should prompt the user to download it. I'll see what I can do about this

**Comment by SRC267** [comment]
Consider wsa pacman as an option for this too.

**Comment by infinitepower18** [comment]
As Microsoft has discontinued work on the subsystem, this application is now in maintenance mode, meaning no new updates will be released apart from bug fixes. For more information please see #22. Thank you for your understanding and sorry if this decision disappointed you.
