### ISSUE TITLE
Assign a different file manager, user preferred? 

### ISSUE THREAD

**Issue by stonespider** [infinitepower18/WSA-SystemControl#6]
### Describe your request

I'm using google 'Files' app and want to set it as my default file manager.
![image](https://github.com/infinitepower18/WSA-SystemControl/assets/101170571/6843cd70-6f7f-451b-b350-bc5954bc9dc2)

**Comment by infinitepower18** [comment]
As Microsoft has discontinued work on the subsystem, this application is now in maintenance mode, meaning no new updates will be released apart from bug fixes. For more information please see #22. Thank you for your understanding and sorry if this decision disappointed you.
